### ISSUE TITLE
Initial spec review

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-promise-allSettled#18]
@jasonwilliams and @rpamely wrote the initial spec (https://github.com/tc39/proposal-promise-allSettled/pull/14). 👍🏻

Along the way, they ran into some things that were unclear in the existing spec, and had some small questions. I’m going to file separate issues for them and collect them all here, so that everyone can learn from the answers.

**Comment by jasonwilliams** [comment]
We have reviewed it again and it looks fine, the only issue is tidying up the duplication between the resolve functions but this shouldn't stop it from going to stage 2 in our opinion.
