### ISSUE TITLE
Missleading sentence

### ISSUE THREAD

**Issue by GrosSacASac** [tc39/proposal-promise-allSettled#28]
> Due to the short circuit nature of Promise.all() any rejected promise will cancel the entire operation and return a rejection.

Cancel is miss-leading, especially nowadays with AbortController that exist.  I propose to rephrase like :

Due to the short circuit nature of Promise.all() any rejected promise will make the resulting promise reject while silently discarding other results.

**Comment by mathiasbynens** [comment]
@GrosSacASac Good point. Care to submit a PR?
