### ISSUE TITLE
Test262 coverage note

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-promise-allSettled#33]
Reviewing the spec text, I was reminded of the extra care we put in to making Promise.all behave reasonably in the face of weird promise subclasses and similar scenarios, e.g. with the [[AlreadyResolved]] internal slot. I think those are pretty exhaustively tested in existing test262, and this issue is about making sure the same is done for Promise.allSettled.

When writing test262 tests, please be sure to test all the same weird edge cases that can occur as with Promise.all---plus the extra ones introduced by the reject element function and its interactions.

(I'm fine if the champions would like to close this issue and roll it into #11, or move it to the test262 repo. But I'm raising it here for visibility to start with.)

**Comment by rpamely** [comment]
I am going to copy this to the test262 issue and close this. (https://github.com/tc39/test262/issues/2112)
