### ISSUE TITLE
Document more use cases

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-promise-allSettled#5]
Good to have references to other implementations, but it would be nice to have a little more information inline, including some realistic use cases.

**Comment by ljharb** [comment]
```js
const requests = URLs.map(x => fetch(x));
Promise.allSettled(requests).finally(() => {
  console.log('all requests are completed: either failed or succeeded, i don‘t care');
  removeLoadingIndicator();
});
```

**Comment by jasonwilliams** [comment]
Thanks @ljharb I've added that to the ReadMe
https://github.com/jasonwilliams/proposal-promise-allSettled#real-world-scenarios

@littledan do you feel we need a few more?

**Comment by domenic** [comment]
It might be good to outline why in that example `all` is not appropriate. Although it is pretty clear if you know the methods yourself, spelling it out will help people who are less involved understand things at a glance.

**Comment by ljharb** [comment]
@domenic good point; updated.

**Comment by littledan** [comment]
More examples eventually would be good. I haven't been perfect about this in my repositories' explainers, but at least in some committee presentations it should be explained a little more. Maybe others can fill in suggestions here, or you can find some in existing library documentation.

**Comment by mathiasbynens** [comment]
Closing as the README now contains several examples.
